name: Continuous Integration

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/cache/restore@v4
        id: cache-npm
        with:
          path: ~/.npm
          key: npm-

      - name: Install node_modules
        run: npm ci --ignore-scripts

      - name: Run tests
        run: npm run test

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install node_modules
        run: npm ci

      - name: Cypress Run
        run: npx cypress run --project ./e2e