name: Test

on:
  push:
    branches:
      - main

jobs:

   install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: npm ci

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

  unit-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm run test:ci

  build:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/cache/restore@v4
        id: cache-npm
        with:
          path: ~/.npm
          key: npm-

      - name: Install node_modules
        run: npm ci --ignore-scripts

      - name: Build application
        run: npm run build

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Start the application
      run: npm start &

    - name: Wait for the application to start
      run: sleep 10

    - name: Run E2E tests
      run: npm run cypress:run